### ISSUE TITLE
Min order amount doesn't work properly

### ISSUE THREAD

**Issue by rwaynick** [jobthomas/your-first-pr#7] opened 2020-02-13 14:27 UTC
<img width="814" alt="Screen Shot 2020-02-13 at 09 25 55" src="https://user-images.githubusercontent.com/10882502/74444474-eb41fd80-4e42-11ea-9c4c-50512d5dba08.png">

**Comment by jobthomas** [comment] 2020-02-13 14:29
Duplicate of #4

**Closed as completed by jobthomas** 2020-02-13 14:29 UTC
