### ISSUE TITLE
Can't set minimum order value in settings

### ISSUE THREAD

**Issue by hannahswain** [jobthomas/your-first-pr#2] opened 2020-02-13 14:22 UTC
In WooCommerce > Settings > General, there isn't a way to edit the field to modify the minimum order:

![Edit](https://d.pr/i/cdDWal+)
Full size: https://d.pr/i/cdDWal

**Comment by jobthomas** [comment] 2020-02-13 14:23
Duplicate of #1

**Closed as completed by jobthomas** 2020-02-13 14:23 UTC
